-- Adopt snake_case for every physical name in the database.
--
-- Migration 0002 moved tables from PascalCase to camelCase. This finishes the
-- job and moves them to snake_case, which is the Postgres convention and the
-- only casing that does not require double-quoting every identifier by hand:
-- Postgres folds unquoted identifiers to lower case, so `select * from
-- user_achievement` just works, where "userAchievement" always needed quotes.
--
-- 0002 is deliberately left in place rather than rewritten. It has already been
-- applied to real databases, and rewriting an applied migration would strand
-- any environment sitting on camelCase with no path forward. Replaying from
-- scratch gives PascalCase -> camelCase -> snake_case, which is one extra hop
-- and always lands in the same place.
--
-- Covered here:
--   * 186 tables    -- "userAchievement" -> "user_achievement"
--   * 135 enum types -- "ActivityType"    -> "activity_type"
--   * 516 constraints (primary keys, uniques, foreign keys)
--
-- COLUMN names are intentionally NOT touched. They are still camelCase
-- ("userId", "createdAt"), which is why the constraint names below read as
-- hybrids -- "user_skill_userId_user_id_fk" is the table part renamed and the
-- column part left alone. That is exactly the name Drizzle derives from the
-- current schema, so the snapshot and the database agree. Renaming columns is a
-- separate, much larger change and belongs in its own migration.
--
-- Every rename is derived from the Drizzle snapshot rather than by pattern
-- matching on names, so a column that happens to share a table's name cannot be
-- rewritten by accident. Each is guarded (rename only when the old name exists
-- and the new one is free), making this safe to re-run and safe against a
-- partially-renamed database. The whole thing is one DO block, which Postgres
-- runs as a single statement: it either fully applies or fully rolls back.
DO $$
DECLARE
    r record;
BEGIN
    DROP TABLE IF EXISTS pg_temp._t;
    DROP TABLE IF EXISTS pg_temp._c;
    DROP TABLE IF EXISTS pg_temp._e;
    CREATE TEMP TABLE _t (old_name text PRIMARY KEY, new_name text NOT NULL);
    CREATE TEMP TABLE _c (tbl text NOT NULL, old_name text NOT NULL, new_name text NOT NULL);
    CREATE TEMP TABLE _e (old_name text PRIMARY KEY, new_name text NOT NULL);

    INSERT INTO _t (old_name, new_name) VALUES
        ('activityEntry', 'activity_entry'),
        ('adminAccess', 'admin_access'),
        ('adminAuditLog', 'admin_audit_log'),
        ('adminDashboardStats', 'admin_dashboard_stats'),
        ('adminInvitation', 'admin_invitation'),
        ('adminNotification', 'admin_notification'),
        ('adminSystemSettings', 'admin_system_settings'),
        ('applicationActivity', 'application_activity'),
        ('assessmentCertificate', 'assessment_certificate'),
        ('assessmentQuestion', 'assessment_question'),
        ('assessmentSubModule', 'assessment_sub_module'),
        ('assessmentTopic', 'assessment_topic'),
        ('backgroundJob', 'background_job'),
        ('classEnrollment', 'class_enrollment'),
        ('codeEvaluation', 'code_evaluation'),
        ('communityPostBookmark', 'community_post_bookmark'),
        ('companyFollower', 'company_follower'),
        ('companyInvitation', 'company_invitation'),
        ('companyInvoice', 'company_invoice'),
        ('companyMember', 'company_member'),
        ('companyPayment', 'company_payment'),
        ('companySubscription', 'company_subscription'),
        ('companyUniversityLink', 'company_university_link'),
        ('coverLetter', 'cover_letter'),
        ('creditRequest', 'credit_request'),
        ('creditTransaction', 'credit_transaction'),
        ('creditTransfer', 'credit_transfer'),
        ('creditTransferOut', 'credit_transfer_out'),
        ('dailyActivity', 'daily_activity'),
        ('examAnswer', 'exam_answer'),
        ('examAttempt', 'exam_attempt'),
        ('followRequest', 'follow_request'),
        ('interviewPlanPurchase', 'interview_plan_purchase'),
        ('interviewPrepProgress', 'interview_prep_progress'),
        ('interviewProcess', 'interview_process'),
        ('interviewProcessTemplate', 'interview_process_template'),
        ('interviewRound', 'interview_round'),
        ('jobApplication', 'job_application'),
        ('jobInterviewAssistant', 'job_interview_assistant'),
        ('jobMockSession', 'job_mock_session'),
        ('jobRecommendation', 'job_recommendation'),
        ('knowMeApiRequest', 'know_me_api_request'),
        ('knowMeChatMessage', 'know_me_chat_message'),
        ('knowMeChatSession', 'know_me_chat_session'),
        ('knowMeCreditTransaction', 'know_me_credit_transaction'),
        ('knowMeEmbedding', 'know_me_embedding'),
        ('knowMeEmbeddingJob', 'know_me_embedding_job'),
        ('knowMeExternalData', 'know_me_external_data'),
        ('knowMePersonalData', 'know_me_personal_data'),
        ('knowMePlatformConnection', 'know_me_platform_connection'),
        ('knowMePrivacySettings', 'know_me_privacy_settings'),
        ('knowMeProfile', 'know_me_profile'),
        ('knowMeProfileView', 'know_me_profile_view'),
        ('knowMeQuestionAnalytics', 'know_me_question_analytics'),
        ('memberInvitation', 'member_invitation'),
        ('mockInterviewBookmark', 'mock_interview_bookmark'),
        ('mockInterviewVoice', 'mock_interview_voice'),
        ('mockVoiceRating', 'mock_voice_rating'),
        ('mockVoiceSession', 'mock_voice_session'),
        ('openSourceProject', 'open_source_project'),
        ('osCertification', 'os_certification'),
        ('osCertificationExam', 'os_certification_exam'),
        ('osContribution', 'os_contribution'),
        ('osEarningsTransaction', 'os_earnings_transaction'),
        ('osGitHubProfile', 'os_git_hub_profile'),
        ('osIssue', 'os_issue'),
        ('osLearnLesson', 'os_learn_lesson'),
        ('osLearnModule', 'os_learn_module'),
        ('osLearnPracticeCompletion', 'os_learn_practice_completion'),
        ('osLearnPracticeProject', 'os_learn_practice_project'),
        ('osLearnPracticeSubmission', 'os_learn_practice_submission'),
        ('osLearnPracticeTask', 'os_learn_practice_task'),
        ('osLearnProgress', 'os_learn_progress'),
        ('osLessonCompletion', 'os_lesson_completion'),
        ('osProjectContributor', 'os_project_contributor'),
        ('osProjectLeaderboard', 'os_project_leaderboard'),
        ('osProjectSetupGuide', 'os_project_setup_guide'),
        ('pathfinderCodingSubmission', 'pathfinder_coding_submission'),
        ('pathfinderDailySession', 'pathfinder_daily_session'),
        ('pathfinderGoal', 'pathfinder_goal'),
        ('pathfinderGoalPurchase', 'pathfinder_goal_purchase'),
        ('pathfinderGroup', 'pathfinder_group'),
        ('pathfinderQuizAttempt', 'pathfinder_quiz_attempt'),
        ('pathfinderSubGoal', 'pathfinder_sub_goal'),
        ('pathfinderUsageLedger', 'pathfinder_usage_ledger'),
        ('pathfinderVerification', 'pathfinder_verification'),
        ('portfolioProject', 'portfolio_project'),
        ('practiceAnswer', 'practice_answer'),
        ('practiceAttempt', 'practice_attempt'),
        ('practiceLeaderboard', 'practice_leaderboard'),
        ('practiceModuleProgress', 'practice_module_progress'),
        ('practiceProblem', 'practice_problem'),
        ('practiceUserSession', 'practice_user_session'),
        ('profileView', 'profile_view'),
        ('projectCategory', 'project_category'),
        ('projectIdea', 'project_idea'),
        ('projectIdeaUpvote', 'project_idea_upvote'),
        ('projectLink', 'project_link'),
        ('projectMedia', 'project_media'),
        ('projectTechnology', 'project_technology'),
        ('projectV2', 'project_v2'),
        ('projectV2Bookmark', 'project_v2_bookmark'),
        ('projectV2Error', 'project_v2_error'),
        ('projectV2ErrorVote', 'project_v2_error_vote'),
        ('projectV2FeatureSuggestion', 'project_v2_feature_suggestion'),
        ('projectV2GlobalLeaderboard', 'project_v2_global_leaderboard'),
        ('projectV2GuidedSession', 'project_v2_guided_session'),
        ('projectV2Invitation', 'project_v2_invitation'),
        ('projectV2KnowledgeBase', 'project_v2_knowledge_base'),
        ('projectV2Leaderboard', 'project_v2_leaderboard'),
        ('projectV2Member', 'project_v2_member'),
        ('projectV2MockSession', 'project_v2_mock_session'),
        ('projectV2Page', 'project_v2_page'),
        ('projectV2Quiz', 'project_v2_quiz'),
        ('projectV2QuizAnswer', 'project_v2_quiz_answer'),
        ('projectV2QuizAttempt', 'project_v2_quiz_attempt'),
        ('projectV2QuizQuestion', 'project_v2_quiz_question'),
        ('projectV2Resource', 'project_v2_resource'),
        ('projectV2Sprint', 'project_v2_sprint'),
        ('projectV2SprintSuggestion', 'project_v2_sprint_suggestion'),
        ('projectV2StandupConfig', 'project_v2_standup_config'),
        ('projectV2StandupEntry', 'project_v2_standup_entry'),
        ('projectV2Submission', 'project_v2_submission'),
        ('projectV2Task', 'project_v2_task'),
        ('projectV2TaskDetail', 'project_v2_task_detail'),
        ('questionAnswer', 'question_answer'),
        ('randomPracticeSession', 'random_practice_session'),
        ('recentActivity', 'recent_activity'),
        ('resumeDraft', 'resume_draft'),
        ('resumeTemplate', 'resume_template'),
        ('resumeTemplateGeneration', 'resume_template_generation'),
        ('savedJob', 'saved_job'),
        ('skillEndorsement', 'skill_endorsement'),
        ('socialConnection', 'social_connection'),
        ('socialLink', 'social_link'),
        ('streakReward', 'streak_reward'),
        ('studentUniversityLink', 'student_university_link'),
        ('studioChatMessage', 'studio_chat_message'),
        ('studioCodeBlock', 'studio_code_block'),
        ('studioFlashcardDeck', 'studio_flashcard_deck'),
        ('studioFlashcardSession', 'studio_flashcard_session'),
        ('studioMediaBlock', 'studio_media_block'),
        ('studioQuiz', 'studio_quiz'),
        ('studioQuizAttempt', 'studio_quiz_attempt'),
        ('studioStep', 'studio_step'),
        ('subTransaction', 'sub_transaction'),
        ('templatePurchase', 'template_purchase'),
        ('universityAssignment', 'university_assignment'),
        ('universityClass', 'university_class'),
        ('universityCreditTransaction', 'university_credit_transaction'),
        ('universityInvitation', 'university_invitation'),
        ('universityInvoice', 'university_invoice'),
        ('universityJob', 'university_job'),
        ('universityMember', 'university_member'),
        ('universityMemberInvitation', 'university_member_invitation'),
        ('universityPayment', 'university_payment'),
        ('universitySubmission', 'university_submission'),
        ('universitySubscription', 'university_subscription'),
        ('userAchievement', 'user_achievement'),
        ('userAssessmentStats', 'user_assessment_stats'),
        ('userDSATrackingEntry', 'user_dsa_tracking_entry'),
        ('userEducation', 'user_education'),
        ('userExamSet', 'user_exam_set'),
        ('userExamSetAnswer', 'user_exam_set_answer'),
        ('userExamSetAttempt', 'user_exam_set_attempt'),
        ('userExamSetLike', 'user_exam_set_like'),
        ('userExamSetPurchase', 'user_exam_set_purchase'),
        ('userExamSetQuestion', 'user_exam_set_question'),
        ('userLevelProgress', 'user_level_progress'),
        ('userOSStats', 'user_os_stats'),
        ('userPracticeSet', 'user_practice_set'),
        ('userPracticeSetAnswer', 'user_practice_set_answer'),
        ('userPracticeSetAttempt', 'user_practice_set_attempt'),
        ('userPracticeSetLike', 'user_practice_set_like'),
        ('userPracticeSetPurchase', 'user_practice_set_purchase'),
        ('userPracticeSetQuestion', 'user_practice_set_question'),
        ('userProfile', 'user_profile'),
        ('userProjectV2Progress', 'user_project_v2_progress'),
        ('userQuestionResponse', 'user_question_response'),
        ('userSkill', 'user_skill'),
        ('userStats', 'user_stats'),
        ('userTaskV2Assessment', 'user_task_v2_assessment'),
        ('userTaskV2DetailAccess', 'user_task_v2_detail_access'),
        ('userTaskV2Status', 'user_task_v2_status'),
        ('workExperience', 'work_experience'),
        ('xpTransaction', 'xp_transaction');

    INSERT INTO _c (tbl, old_name, new_name) VALUES
        ('activity_entry', 'activityEntry_dailyActivityId_dailyActivity_id_fk', 'activity_entry_dailyActivityId_daily_activity_id_fk'),
        ('activity_entry', 'activityEntry_pkey', 'activity_entry_pkey'),
        ('activity_entry', 'activityEntry_userId_user_id_fk', 'activity_entry_userId_user_id_fk'),
        ('admin_access', 'adminAccess_pkey', 'admin_access_pkey'),
        ('admin_access', 'adminAccess_userId_unique', 'admin_access_userId_unique'),
        ('admin_access', 'adminAccess_userId_user_id_fk', 'admin_access_userId_user_id_fk'),
        ('admin_audit_log', 'adminAuditLog_adminId_adminAccess_id_fk', 'admin_audit_log_adminId_admin_access_id_fk'),
        ('admin_audit_log', 'adminAuditLog_pkey', 'admin_audit_log_pkey'),
        ('admin_dashboard_stats', 'adminDashboardStats_pkey', 'admin_dashboard_stats_pkey'),
        ('admin_dashboard_stats', 'adminDashboardStats_statType_unique', 'admin_dashboard_stats_statType_unique'),
        ('admin_invitation', 'adminInvitation_code_unique', 'admin_invitation_code_unique'),
        ('admin_invitation', 'adminInvitation_createdById_adminAccess_id_fk', 'admin_invitation_createdById_admin_access_id_fk'),
        ('admin_invitation', 'adminInvitation_pkey', 'admin_invitation_pkey'),
        ('admin_notification', 'adminNotification_pkey', 'admin_notification_pkey'),
        ('admin_system_settings', 'adminSystemSettings_key_unique', 'admin_system_settings_key_unique'),
        ('admin_system_settings', 'adminSystemSettings_pkey', 'admin_system_settings_pkey'),
        ('application_activity', 'applicationActivity_applicationId_jobApplication_id_fk', 'application_activity_applicationId_job_application_id_fk'),
        ('application_activity', 'applicationActivity_pkey', 'application_activity_pkey'),
        ('application_activity', 'applicationActivity_userId_user_id_fk', 'application_activity_userId_user_id_fk'),
        ('assessment_certificate', 'assessmentCertificate_certificateId_unique', 'assessment_certificate_certificateId_unique'),
        ('assessment_certificate', 'assessmentCertificate_pkey', 'assessment_certificate_pkey'),
        ('assessment_certificate', 'assessmentCertificate_userId_user_id_fk', 'assessment_certificate_userId_user_id_fk'),
        ('assessment_question', 'assessmentQuestion_pkey', 'assessment_question_pkey'),
        ('assessment_question', 'assessmentQuestion_subModuleId_assessmentSubModule_id_fk', 'assessment_question_subModuleId_assessment_sub_module_id_fk'),
        ('assessment_question', 'assessmentQuestion_topicId_assessmentTopic_id_fk', 'assessment_question_topicId_assessment_topic_id_fk'),
        ('assessment_sub_module', 'assessmentSubModule_pkey', 'assessment_sub_module_pkey'),
        ('assessment_sub_module', 'assessmentSubModule_topicId_assessmentTopic_id_fk', 'assessment_sub_module_topicId_assessment_topic_id_fk'),
        ('assessment_topic', 'assessmentTopic_pkey', 'assessment_topic_pkey'),
        ('assessment_topic', 'assessmentTopic_slug_unique', 'assessment_topic_slug_unique'),
        ('background_job', 'backgroundJob_jobId_unique', 'background_job_jobId_unique'),
        ('background_job', 'backgroundJob_pkey', 'background_job_pkey'),
        ('background_job', 'backgroundJob_userId_user_id_fk', 'background_job_userId_user_id_fk'),
        ('class_enrollment', 'classEnrollment_classId_universityClass_id_fk', 'class_enrollment_classId_university_class_id_fk'),
        ('class_enrollment', 'classEnrollment_pkey', 'class_enrollment_pkey'),
        ('class_enrollment', 'classEnrollment_studentLinkId_studentUniversityLink_id_fk', 'class_enrollment_studentLinkId_student_university_link_id_fk'),
        ('code_evaluation', 'codeEvaluation_interviewId_jobInterviewAssistant_id_fk', 'code_evaluation_interviewId_job_interview_assistant_id_fk'),
        ('code_evaluation', 'codeEvaluation_pkey', 'code_evaluation_pkey'),
        ('community_post_bookmark', 'communityPostBookmark_pkey', 'community_post_bookmark_pkey'),
        ('community_post_bookmark', 'communityPostBookmark_userId_user_id_fk', 'community_post_bookmark_userId_user_id_fk'),
        ('company_follower', 'companyFollower_companyId_company_id_fk', 'company_follower_companyId_company_id_fk'),
        ('company_follower', 'companyFollower_pkey', 'company_follower_pkey'),
        ('company_follower', 'companyFollower_userId_user_id_fk', 'company_follower_userId_user_id_fk'),
        ('company_invitation', 'companyInvitation_companyId_company_id_fk', 'company_invitation_companyId_company_id_fk'),
        ('company_invitation', 'companyInvitation_inviteCode_unique', 'company_invitation_inviteCode_unique'),
        ('company_invitation', 'companyInvitation_pkey', 'company_invitation_pkey'),
        ('company_invoice', 'companyInvoice_companyId_company_id_fk', 'company_invoice_companyId_company_id_fk'),
        ('company_invoice', 'companyInvoice_invoiceNumber_unique', 'company_invoice_invoiceNumber_unique'),
        ('company_invoice', 'companyInvoice_paymentId_companyPayment_id_fk', 'company_invoice_paymentId_company_payment_id_fk'),
        ('company_invoice', 'companyInvoice_paymentId_unique', 'company_invoice_paymentId_unique'),
        ('company_invoice', 'companyInvoice_pkey', 'company_invoice_pkey'),
        ('company_member', 'companyMember_companyId_company_id_fk', 'company_member_companyId_company_id_fk'),
        ('company_member', 'companyMember_pkey', 'company_member_pkey'),
        ('company_member', 'companyMember_userId_user_id_fk', 'company_member_userId_user_id_fk'),
        ('company_payment', 'companyPayment_companyId_company_id_fk', 'company_payment_companyId_company_id_fk'),
        ('company_payment', 'companyPayment_dodoCheckoutSessionId_unique', 'company_payment_dodoCheckoutSessionId_unique'),
        ('company_payment', 'companyPayment_dodoPaymentId_unique', 'company_payment_dodoPaymentId_unique'),
        ('company_payment', 'companyPayment_pkey', 'company_payment_pkey'),
        ('company_payment', 'companyPayment_subscriptionId_companySubscription_id_fk', 'company_payment_subscriptionId_company_subscription_id_fk'),
        ('company_subscription', 'companySubscription_companyId_company_id_fk', 'company_subscription_companyId_company_id_fk'),
        ('company_subscription', 'companySubscription_companyId_unique', 'company_subscription_companyId_unique'),
        ('company_subscription', 'companySubscription_dodoSubscriptionId_unique', 'company_subscription_dodoSubscriptionId_unique'),
        ('company_subscription', 'companySubscription_pkey', 'company_subscription_pkey'),
        ('company_university_link', 'companyUniversityLink_pkey', 'company_university_link_pkey'),
        ('company_university_link', 'companyUniversityLink_referralCode_unique', 'company_university_link_referralCode_unique'),
        ('company_university_link', 'companyUniversityLink_universityId_university_id_fk', 'company_university_link_universityId_university_id_fk'),
        ('cover_letter', 'coverLetter_pkey', 'cover_letter_pkey'),
        ('cover_letter', 'coverLetter_userId_user_id_fk', 'cover_letter_userId_user_id_fk'),
        ('credit_request', 'creditRequest_pkey', 'credit_request_pkey'),
        ('credit_request', 'creditRequest_userId_user_id_fk', 'credit_request_userId_user_id_fk'),
        ('credit_transaction', 'creditTransaction_pkey', 'credit_transaction_pkey'),
        ('credit_transaction', 'creditTransaction_userId_user_id_fk', 'credit_transaction_userId_user_id_fk'),
        ('credit_transfer', 'creditTransfer_pkey', 'credit_transfer_pkey'),
        ('credit_transfer', 'creditTransfer_receiverId_user_id_fk', 'credit_transfer_receiverId_user_id_fk'),
        ('credit_transfer', 'creditTransfer_senderId_user_id_fk', 'credit_transfer_senderId_user_id_fk'),
        ('credit_transfer', 'creditTransfer_transferReference_unique', 'credit_transfer_transferReference_unique'),
        ('credit_transfer_out', 'creditTransferOut_pkey', 'credit_transfer_out_pkey'),
        ('credit_transfer_out', 'creditTransferOut_userId_user_id_fk', 'credit_transfer_out_userId_user_id_fk'),
        ('daily_activity', 'dailyActivity_date_unique', 'daily_activity_date_unique'),
        ('daily_activity', 'dailyActivity_pkey', 'daily_activity_pkey'),
        ('daily_activity', 'dailyActivity_userId_user_id_fk', 'daily_activity_userId_user_id_fk'),
        ('exam_answer', 'examAnswer_attemptId_examAttempt_id_fk', 'exam_answer_attemptId_exam_attempt_id_fk'),
        ('exam_answer', 'examAnswer_pkey', 'exam_answer_pkey'),
        ('exam_answer', 'examAnswer_questionId_assessmentQuestion_id_fk', 'exam_answer_questionId_assessment_question_id_fk'),
        ('exam_attempt', 'examAttempt_certificateId_unique', 'exam_attempt_certificateId_unique'),
        ('exam_attempt', 'examAttempt_pkey', 'exam_attempt_pkey'),
        ('exam_attempt', 'examAttempt_topicId_assessmentTopic_id_fk', 'exam_attempt_topicId_assessment_topic_id_fk'),
        ('exam_attempt', 'examAttempt_userId_user_id_fk', 'exam_attempt_userId_user_id_fk'),
        ('follow_request', 'followRequest_pkey', 'follow_request_pkey'),
        ('follow_request', 'followRequest_receiverId_user_id_fk', 'follow_request_receiverId_user_id_fk'),
        ('follow_request', 'followRequest_senderId_user_id_fk', 'follow_request_senderId_user_id_fk'),
        ('interview_plan_purchase', 'interviewPlanPurchase_interviewPlanId_jobInterviewAssistant_id_fk', 'interview_plan_purchase_interviewPlanId_job_interview_assistant_id_fk'),
        ('interview_plan_purchase', 'interviewPlanPurchase_newInterviewPlanId_jobInterviewAssistant_id_fk', 'interview_plan_purchase_newInterviewPlanId_job_interview_assistant_id_fk'),
        ('interview_plan_purchase', 'interviewPlanPurchase_pkey', 'interview_plan_purchase_pkey'),
        ('interview_prep_progress', 'interviewPrepProgress_applicationId_unique', 'interview_prep_progress_applicationId_unique'),
        ('interview_prep_progress', 'interviewPrepProgress_pkey', 'interview_prep_progress_pkey'),
        ('interview_prep_progress', 'interviewPrepProgress_userId_user_id_fk', 'interview_prep_progress_userId_user_id_fk'),
        ('interview_process', 'interviewProcess_companyId_company_id_fk', 'interview_process_companyId_company_id_fk'),
        ('interview_process', 'interviewProcess_pkey', 'interview_process_pkey'),
        ('interview_process_template', 'interviewProcessTemplate_pkey', 'interview_process_template_pkey'),
        ('interview_round', 'interviewRound_pkey', 'interview_round_pkey'),
        ('interview_round', 'interviewRound_processId_interviewProcess_id_fk', 'interview_round_processId_interview_process_id_fk'),
        ('job', 'job_postedById_companyMember_id_fk', 'job_postedById_company_member_id_fk'),
        ('job_application', 'jobApplication_jobId_job_id_fk', 'job_application_jobId_job_id_fk'),
        ('job_application', 'jobApplication_pkey', 'job_application_pkey'),
        ('job_application', 'jobApplication_userId_user_id_fk', 'job_application_userId_user_id_fk'),
        ('job_interview_assistant', 'jobInterviewAssistant_pkey', 'job_interview_assistant_pkey'),
        ('job_interview_assistant', 'jobInterviewAssistant_slug_unique', 'job_interview_assistant_slug_unique'),
        ('job_interview_assistant', 'jobInterviewAssistant_userId_user_id_fk', 'job_interview_assistant_userId_user_id_fk'),
        ('job_mock_session', 'jobMockSession_companyId_company_id_fk', 'job_mock_session_companyId_company_id_fk'),
        ('job_mock_session', 'jobMockSession_conversationId_unique', 'job_mock_session_conversationId_unique'),
        ('job_mock_session', 'jobMockSession_pkey', 'job_mock_session_pkey'),
        ('job_mock_session', 'jobMockSession_roundId_interviewRound_id_fk', 'job_mock_session_roundId_interview_round_id_fk'),
        ('job_mock_session', 'jobMockSession_userId_user_id_fk', 'job_mock_session_userId_user_id_fk'),
        ('job_recommendation', 'jobRecommendation_jobId_job_id_fk', 'job_recommendation_jobId_job_id_fk'),
        ('job_recommendation', 'jobRecommendation_pkey', 'job_recommendation_pkey'),
        ('job_recommendation', 'jobRecommendation_userId_user_id_fk', 'job_recommendation_userId_user_id_fk'),
        ('know_me_api_request', 'knowMeApiRequest_pkey', 'know_me_api_request_pkey'),
        ('know_me_api_request', 'knowMeApiRequest_profileId_knowMeProfile_id_fk', 'know_me_api_request_profileId_know_me_profile_id_fk'),
        ('know_me_chat_message', 'knowMeChatMessage_pkey', 'know_me_chat_message_pkey'),
        ('know_me_chat_message', 'knowMeChatMessage_sessionId_knowMeChatSession_id_fk', 'know_me_chat_message_sessionId_know_me_chat_session_id_fk'),
        ('know_me_chat_session', 'knowMeChatSession_pkey', 'know_me_chat_session_pkey'),
        ('know_me_chat_session', 'knowMeChatSession_profileId_knowMeProfile_id_fk', 'know_me_chat_session_profileId_know_me_profile_id_fk'),
        ('know_me_chat_session', 'knowMeChatSession_sessionToken_unique', 'know_me_chat_session_sessionToken_unique'),
        ('know_me_chat_session', 'knowMeChatSession_visitorUserId_user_id_fk', 'know_me_chat_session_visitorUserId_user_id_fk'),
        ('know_me_credit_transaction', 'knowMeCreditTransaction_pkey', 'know_me_credit_transaction_pkey'),
        ('know_me_credit_transaction', 'knowMeCreditTransaction_userId_user_id_fk', 'know_me_credit_transaction_userId_user_id_fk'),
        ('know_me_embedding', 'knowMeEmbedding_pkey', 'know_me_embedding_pkey'),
        ('know_me_embedding', 'knowMeEmbedding_profileId_knowMeProfile_id_fk', 'know_me_embedding_profileId_know_me_profile_id_fk'),
        ('know_me_embedding_job', 'knowMeEmbeddingJob_pkey', 'know_me_embedding_job_pkey'),
        ('know_me_embedding_job', 'knowMeEmbeddingJob_profileId_knowMeProfile_id_fk', 'know_me_embedding_job_profileId_know_me_profile_id_fk'),
        ('know_me_external_data', 'knowMeExternalData_connectionId_knowMePlatformConnection_id_fk', 'know_me_external_data_connectionId_know_me_platform_connection_id_fk'),
        ('know_me_external_data', 'knowMeExternalData_pkey', 'know_me_external_data_pkey'),
        ('know_me_external_data', 'knowMeExternalData_profileId_knowMeProfile_id_fk', 'know_me_external_data_profileId_know_me_profile_id_fk'),
        ('know_me_personal_data', 'knowMePersonalData_pkey', 'know_me_personal_data_pkey'),
        ('know_me_personal_data', 'knowMePersonalData_profileId_knowMeProfile_id_fk', 'know_me_personal_data_profileId_know_me_profile_id_fk'),
        ('know_me_platform_connection', 'knowMePlatformConnection_pkey', 'know_me_platform_connection_pkey'),
        ('know_me_platform_connection', 'knowMePlatformConnection_profileId_knowMeProfile_id_fk', 'know_me_platform_connection_profileId_know_me_profile_id_fk'),
        ('know_me_privacy_settings', 'knowMePrivacySettings_pkey', 'know_me_privacy_settings_pkey'),
        ('know_me_privacy_settings', 'knowMePrivacySettings_profileId_knowMeProfile_id_fk', 'know_me_privacy_settings_profileId_know_me_profile_id_fk'),
        ('know_me_privacy_settings', 'knowMePrivacySettings_profileId_unique', 'know_me_privacy_settings_profileId_unique'),
        ('know_me_profile', 'knowMeProfile_apiKey_unique', 'know_me_profile_apiKey_unique'),
        ('know_me_profile', 'knowMeProfile_pkey', 'know_me_profile_pkey'),
        ('know_me_profile', 'knowMeProfile_userId_unique', 'know_me_profile_userId_unique'),
        ('know_me_profile', 'knowMeProfile_userId_user_id_fk', 'know_me_profile_userId_user_id_fk'),
        ('know_me_profile_view', 'knowMeProfileView_pkey', 'know_me_profile_view_pkey'),
        ('know_me_profile_view', 'knowMeProfileView_profileId_knowMeProfile_id_fk', 'know_me_profile_view_profileId_know_me_profile_id_fk'),
        ('know_me_profile_view', 'knowMeProfileView_viewerUserId_user_id_fk', 'know_me_profile_view_viewerUserId_user_id_fk'),
        ('know_me_question_analytics', 'knowMeQuestionAnalytics_askedByUserId_user_id_fk', 'know_me_question_analytics_askedByUserId_user_id_fk'),
        ('know_me_question_analytics', 'knowMeQuestionAnalytics_pkey', 'know_me_question_analytics_pkey'),
        ('know_me_question_analytics', 'knowMeQuestionAnalytics_profileId_knowMeProfile_id_fk', 'know_me_question_analytics_profileId_know_me_profile_id_fk'),
        ('member_invitation', 'memberInvitation_companyId_company_id_fk', 'member_invitation_companyId_company_id_fk'),
        ('member_invitation', 'memberInvitation_inviteCode_unique', 'member_invitation_inviteCode_unique'),
        ('member_invitation', 'memberInvitation_invitedById_companyMember_id_fk', 'member_invitation_invitedById_company_member_id_fk'),
        ('member_invitation', 'memberInvitation_pkey', 'member_invitation_pkey'),
        ('mock_interview_bookmark', 'mockInterviewBookmark_pkey', 'mock_interview_bookmark_pkey'),
        ('mock_interview_bookmark', 'mockInterviewBookmark_userId_user_id_fk', 'mock_interview_bookmark_userId_user_id_fk'),
        ('mock_interview_voice', 'mockInterviewVoice_createdById_user_id_fk', 'mock_interview_voice_createdById_user_id_fk'),
        ('mock_interview_voice', 'mockInterviewVoice_pathfinderSubGoalId_unique', 'mock_interview_voice_pathfinderSubGoalId_unique'),
        ('mock_interview_voice', 'mockInterviewVoice_pkey', 'mock_interview_voice_pkey'),
        ('mock_interview_voice', 'mockInterviewVoice_predefinedId_unique', 'mock_interview_voice_predefinedId_unique'),
        ('mock_voice_rating', 'mockVoiceRating_mockId_mockInterviewVoice_id_fk', 'mock_voice_rating_mockId_mock_interview_voice_id_fk'),
        ('mock_voice_rating', 'mockVoiceRating_pkey', 'mock_voice_rating_pkey'),
        ('mock_voice_rating', 'mockVoiceRating_userId_user_id_fk', 'mock_voice_rating_userId_user_id_fk'),
        ('mock_voice_session', 'mockVoiceSession_conversationId_unique', 'mock_voice_session_conversationId_unique'),
        ('mock_voice_session', 'mockVoiceSession_mockId_mockInterviewVoice_id_fk', 'mock_voice_session_mockId_mock_interview_voice_id_fk'),
        ('mock_voice_session', 'mockVoiceSession_pkey', 'mock_voice_session_pkey'),
        ('mock_voice_session', 'mockVoiceSession_userId_user_id_fk', 'mock_voice_session_userId_user_id_fk'),
        ('open_source_project', 'openSourceProject_createdById_user_id_fk', 'open_source_project_createdById_user_id_fk'),
        ('open_source_project', 'openSourceProject_maintainerId_user_id_fk', 'open_source_project_maintainerId_user_id_fk'),
        ('open_source_project', 'openSourceProject_pkey', 'open_source_project_pkey'),
        ('open_source_project', 'openSourceProject_slug_unique', 'open_source_project_slug_unique'),
        ('os_certification', 'osCertification_certificateId_unique', 'os_certification_certificateId_unique'),
        ('os_certification', 'osCertification_pkey', 'os_certification_pkey'),
        ('os_certification', 'osCertification_userId_user_id_fk', 'os_certification_userId_user_id_fk'),
        ('os_certification_exam', 'osCertificationExam_pkey', 'os_certification_exam_pkey'),
        ('os_certification_exam', 'osCertificationExam_userId_user_id_fk', 'os_certification_exam_userId_user_id_fk'),
        ('os_contribution', 'osContribution_issueId_osIssue_id_fk', 'os_contribution_issueId_os_issue_id_fk'),
        ('os_contribution', 'osContribution_pkey', 'os_contribution_pkey'),
        ('os_contribution', 'osContribution_projectId_openSourceProject_id_fk', 'os_contribution_projectId_open_source_project_id_fk'),
        ('os_contribution', 'osContribution_reviewedById_user_id_fk', 'os_contribution_reviewedById_user_id_fk'),
        ('os_contribution', 'osContribution_userId_user_id_fk', 'os_contribution_userId_user_id_fk'),
        ('os_earnings_transaction', 'osEarningsTransaction_pkey', 'os_earnings_transaction_pkey'),
        ('os_earnings_transaction', 'osEarningsTransaction_userId_user_id_fk', 'os_earnings_transaction_userId_user_id_fk'),
        ('os_git_hub_profile', 'osGitHubProfile_githubId_unique', 'os_git_hub_profile_githubId_unique'),
        ('os_git_hub_profile', 'osGitHubProfile_pkey', 'os_git_hub_profile_pkey'),
        ('os_git_hub_profile', 'osGitHubProfile_userId_unique', 'os_git_hub_profile_userId_unique'),
        ('os_git_hub_profile', 'osGitHubProfile_userId_user_id_fk', 'os_git_hub_profile_userId_user_id_fk'),
        ('os_issue', 'osIssue_assignedToId_user_id_fk', 'os_issue_assignedToId_user_id_fk'),
        ('os_issue', 'osIssue_pkey', 'os_issue_pkey'),
        ('os_issue', 'osIssue_projectId_openSourceProject_id_fk', 'os_issue_projectId_open_source_project_id_fk'),
        ('os_learn_lesson', 'osLearnLesson_moduleId_osLearnModule_id_fk', 'os_learn_lesson_moduleId_os_learn_module_id_fk'),
        ('os_learn_lesson', 'osLearnLesson_pkey', 'os_learn_lesson_pkey'),
        ('os_learn_module', 'osLearnModule_pkey', 'os_learn_module_pkey'),
        ('os_learn_module', 'osLearnModule_slug_unique', 'os_learn_module_slug_unique'),
        ('os_learn_practice_completion', 'osLearnPracticeCompletion_pkey', 'os_learn_practice_completion_pkey'),
        ('os_learn_practice_completion', 'osLearnPracticeCompletion_projectId_osLearnPracticeProject_id_fk', 'os_learn_practice_completion_projectId_os_learn_practice_project_id_fk'),
        ('os_learn_practice_project', 'osLearnPracticeProject_pkey', 'os_learn_practice_project_pkey'),
        ('os_learn_practice_project', 'osLearnPracticeProject_slug_unique', 'os_learn_practice_project_slug_unique'),
        ('os_learn_practice_submission', 'osLearnPracticeSubmission_pkey', 'os_learn_practice_submission_pkey'),
        ('os_learn_practice_submission', 'osLearnPracticeSubmission_taskId_osLearnPracticeTask_id_fk', 'os_learn_practice_submission_taskId_os_learn_practice_task_id_fk'),
        ('os_learn_practice_task', 'osLearnPracticeTask_pkey', 'os_learn_practice_task_pkey'),
        ('os_learn_practice_task', 'osLearnPracticeTask_projectId_osLearnPracticeProject_id_fk', 'os_learn_practice_task_projectId_os_learn_practice_project_id_fk'),
        ('os_learn_progress', 'osLearnProgress_moduleId_osLearnModule_id_fk', 'os_learn_progress_moduleId_os_learn_module_id_fk'),
        ('os_learn_progress', 'osLearnProgress_pkey', 'os_learn_progress_pkey'),
        ('os_learn_progress', 'osLearnProgress_userId_user_id_fk', 'os_learn_progress_userId_user_id_fk'),
        ('os_lesson_completion', 'osLessonCompletion_lessonId_osLearnLesson_id_fk', 'os_lesson_completion_lessonId_os_learn_lesson_id_fk'),
        ('os_lesson_completion', 'osLessonCompletion_pkey', 'os_lesson_completion_pkey'),
        ('os_lesson_completion', 'osLessonCompletion_userId_user_id_fk', 'os_lesson_completion_userId_user_id_fk'),
        ('os_project_contributor', 'osProjectContributor_pkey', 'os_project_contributor_pkey'),
        ('os_project_contributor', 'osProjectContributor_projectId_openSourceProject_id_fk', 'os_project_contributor_projectId_open_source_project_id_fk'),
        ('os_project_contributor', 'osProjectContributor_userId_user_id_fk', 'os_project_contributor_userId_user_id_fk'),
        ('os_project_leaderboard', 'osProjectLeaderboard_pkey', 'os_project_leaderboard_pkey'),
        ('os_project_leaderboard', 'osProjectLeaderboard_projectId_openSourceProject_id_fk', 'os_project_leaderboard_projectId_open_source_project_id_fk'),
        ('os_project_leaderboard', 'osProjectLeaderboard_userId_user_id_fk', 'os_project_leaderboard_userId_user_id_fk'),
        ('os_project_setup_guide', 'osProjectSetupGuide_pkey', 'os_project_setup_guide_pkey'),
        ('os_project_setup_guide', 'osProjectSetupGuide_projectId_openSourceProject_id_fk', 'os_project_setup_guide_projectId_open_source_project_id_fk'),
        ('os_project_setup_guide', 'osProjectSetupGuide_projectId_unique', 'os_project_setup_guide_projectId_unique'),
        ('pathfinder_coding_submission', 'pathfinderCodingSubmission_goalId_pathfinderGoal_id_fk', 'pathfinder_coding_submission_goalId_pathfinder_goal_id_fk'),
        ('pathfinder_coding_submission', 'pathfinderCodingSubmission_pkey', 'pathfinder_coding_submission_pkey'),
        ('pathfinder_daily_session', 'pathfinderDailySession_goalId_pathfinderGoal_id_fk', 'pathfinder_daily_session_goalId_pathfinder_goal_id_fk'),
        ('pathfinder_daily_session', 'pathfinderDailySession_pkey', 'pathfinder_daily_session_pkey'),
        ('pathfinder_goal', 'pathfinderGoal_groupId_pathfinderGroup_id_fk', 'pathfinder_goal_groupId_pathfinder_group_id_fk'),
        ('pathfinder_goal', 'pathfinderGoal_pkey', 'pathfinder_goal_pkey'),
        ('pathfinder_goal', 'pathfinderGoal_userId_user_id_fk', 'pathfinder_goal_userId_user_id_fk'),
        ('pathfinder_goal_purchase', 'pathfinderGoalPurchase_buyerId_user_id_fk', 'pathfinder_goal_purchase_buyerId_user_id_fk'),
        ('pathfinder_goal_purchase', 'pathfinderGoalPurchase_goalId_pathfinderGoal_id_fk', 'pathfinder_goal_purchase_goalId_pathfinder_goal_id_fk'),
        ('pathfinder_goal_purchase', 'pathfinderGoalPurchase_pkey', 'pathfinder_goal_purchase_pkey'),
        ('pathfinder_group', 'pathfinderGroup_pkey', 'pathfinder_group_pkey'),
        ('pathfinder_group', 'pathfinderGroup_userId_user_id_fk', 'pathfinder_group_userId_user_id_fk'),
        ('pathfinder_quiz_attempt', 'pathfinderQuizAttempt_goalId_pathfinderGoal_id_fk', 'pathfinder_quiz_attempt_goalId_pathfinder_goal_id_fk'),
        ('pathfinder_quiz_attempt', 'pathfinderQuizAttempt_pkey', 'pathfinder_quiz_attempt_pkey'),
        ('pathfinder_sub_goal', 'pathfinderSubGoal_goalId_pathfinderGoal_id_fk', 'pathfinder_sub_goal_goalId_pathfinder_goal_id_fk'),
        ('pathfinder_sub_goal', 'pathfinderSubGoal_pkey', 'pathfinder_sub_goal_pkey'),
        ('pathfinder_sub_goal', 'pathfinderSubGoal_sessionId_pathfinderDailySession_id_fk', 'pathfinder_sub_goal_sessionId_pathfinder_daily_session_id_fk'),
        ('pathfinder_sub_goal', 'pathfinderSubGoal_studioId_unique', 'pathfinder_sub_goal_studioId_unique'),
        ('pathfinder_usage_ledger', 'pathfinderUsageLedger_goalId_pathfinderGoal_id_fk', 'pathfinder_usage_ledger_goalId_pathfinder_goal_id_fk'),
        ('pathfinder_usage_ledger', 'pathfinderUsageLedger_pkey', 'pathfinder_usage_ledger_pkey'),
        ('pathfinder_verification', 'pathfinderVerification_goalId_pathfinderGoal_id_fk', 'pathfinder_verification_goalId_pathfinder_goal_id_fk'),
        ('pathfinder_verification', 'pathfinderVerification_goalId_unique', 'pathfinder_verification_goalId_unique'),
        ('pathfinder_verification', 'pathfinderVerification_pkey', 'pathfinder_verification_pkey'),
        ('portfolio_project', 'portfolioProject_pkey', 'portfolio_project_pkey'),
        ('portfolio_project', 'portfolioProject_userId_user_id_fk', 'portfolio_project_userId_user_id_fk'),
        ('practice_answer', 'practiceAnswer_attemptId_practiceAttempt_id_fk', 'practice_answer_attemptId_practice_attempt_id_fk'),
        ('practice_answer', 'practiceAnswer_pkey', 'practice_answer_pkey'),
        ('practice_answer', 'practiceAnswer_questionId_assessmentQuestion_id_fk', 'practice_answer_questionId_assessment_question_id_fk'),
        ('practice_attempt', 'practiceAttempt_pkey', 'practice_attempt_pkey'),
        ('practice_attempt', 'practiceAttempt_subModuleId_assessmentSubModule_id_fk', 'practice_attempt_subModuleId_assessment_sub_module_id_fk'),
        ('practice_attempt', 'practiceAttempt_topicId_assessmentTopic_id_fk', 'practice_attempt_topicId_assessment_topic_id_fk'),
        ('practice_attempt', 'practiceAttempt_userId_user_id_fk', 'practice_attempt_userId_user_id_fk'),
        ('practice_leaderboard', 'practiceLeaderboard_pkey', 'practice_leaderboard_pkey'),
        ('practice_leaderboard', 'practiceLeaderboard_userId_user_id_fk', 'practice_leaderboard_userId_user_id_fk'),
        ('practice_module_progress', 'practiceModuleProgress_pkey', 'practice_module_progress_pkey'),
        ('practice_module_progress', 'practiceModuleProgress_userId_user_id_fk', 'practice_module_progress_userId_user_id_fk'),
        ('practice_problem', 'practiceProblem_pkey', 'practice_problem_pkey'),
        ('practice_problem', 'practiceProblem_slug_unique', 'practice_problem_slug_unique'),
        ('practice_user_session', 'practiceUserSession_pkey', 'practice_user_session_pkey'),
        ('practice_user_session', 'practiceUserSession_problemId_practiceProblem_id_fk', 'practice_user_session_problemId_practice_problem_id_fk'),
        ('practice_user_session', 'practiceUserSession_userId_user_id_fk', 'practice_user_session_userId_user_id_fk'),
        ('profile_view', 'profileView_pkey', 'profile_view_pkey'),
        ('profile_view', 'profileView_profileId_userProfile_id_fk', 'profile_view_profileId_user_profile_id_fk'),
        ('project_category', 'projectCategory_pkey', 'project_category_pkey'),
        ('project_category', 'projectCategory_slug_unique', 'project_category_slug_unique'),
        ('project_idea', 'projectIdea_blueprintProjectId_projectV2_id_fk', 'project_idea_blueprintProjectId_project_v2_id_fk'),
        ('project_idea', 'projectIdea_blueprintProjectId_unique', 'project_idea_blueprintProjectId_unique'),
        ('project_idea', 'projectIdea_pkey', 'project_idea_pkey'),
        ('project_idea', 'projectIdea_submittedById_user_id_fk', 'project_idea_submittedById_user_id_fk'),
        ('project_idea_upvote', 'projectIdeaUpvote_pkey', 'project_idea_upvote_pkey'),
        ('project_idea_upvote', 'projectIdeaUpvote_projectIdeaId_projectIdea_id_fk', 'project_idea_upvote_projectIdeaId_project_idea_id_fk'),
        ('project_link', 'projectLink_pkey', 'project_link_pkey'),
        ('project_link', 'projectLink_projectId_portfolioProject_id_fk', 'project_link_projectId_portfolio_project_id_fk'),
        ('project_media', 'projectMedia_pkey', 'project_media_pkey'),
        ('project_media', 'projectMedia_projectId_portfolioProject_id_fk', 'project_media_projectId_portfolio_project_id_fk'),
        ('project_technology', 'projectTechnology_categoryId_projectCategory_id_fk', 'project_technology_categoryId_project_category_id_fk'),
        ('project_technology', 'projectTechnology_pkey', 'project_technology_pkey'),
        ('project_technology', 'projectTechnology_slug_unique', 'project_technology_slug_unique'),
        ('project_v2', 'projectV2_createdBy_user_id_fk', 'project_v2_createdBy_user_id_fk'),
        ('project_v2', 'projectV2_pkey', 'project_v2_pkey'),
        ('project_v2', 'projectV2_slug_unique', 'project_v2_slug_unique'),
        ('project_v2_bookmark', 'projectV2Bookmark_pkey', 'project_v2_bookmark_pkey'),
        ('project_v2_bookmark', 'projectV2Bookmark_userId_user_id_fk', 'project_v2_bookmark_userId_user_id_fk'),
        ('project_v2_error', 'projectV2Error_pkey', 'project_v2_error_pkey'),
        ('project_v2_error', 'projectV2Error_projectId_projectV2_id_fk', 'project_v2_error_projectId_project_v2_id_fk'),
        ('project_v2_error', 'projectV2Error_submittedById_user_id_fk', 'project_v2_error_submittedById_user_id_fk'),
        ('project_v2_error', 'projectV2Error_taskId_projectV2Task_id_fk', 'project_v2_error_taskId_project_v2_task_id_fk'),
        ('project_v2_error_vote', 'projectV2ErrorVote_errorId_projectV2Error_id_fk', 'project_v2_error_vote_errorId_project_v2_error_id_fk'),
        ('project_v2_error_vote', 'projectV2ErrorVote_pkey', 'project_v2_error_vote_pkey'),
        ('project_v2_error_vote', 'projectV2ErrorVote_userId_user_id_fk', 'project_v2_error_vote_userId_user_id_fk'),
        ('project_v2_feature_suggestion', 'projectV2FeatureSuggestion_pkey', 'project_v2_feature_suggestion_pkey'),
        ('project_v2_feature_suggestion', 'projectV2FeatureSuggestion_projectId_projectV2_id_fk', 'project_v2_feature_suggestion_projectId_project_v2_id_fk'),
        ('project_v2_feature_suggestion', 'projectV2FeatureSuggestion_userId_user_id_fk', 'project_v2_feature_suggestion_userId_user_id_fk'),
        ('project_v2_global_leaderboard', 'projectV2GlobalLeaderboard_pkey', 'project_v2_global_leaderboard_pkey'),
        ('project_v2_global_leaderboard', 'projectV2GlobalLeaderboard_userId_unique', 'project_v2_global_leaderboard_userId_unique'),
        ('project_v2_global_leaderboard', 'projectV2GlobalLeaderboard_userId_user_id_fk', 'project_v2_global_leaderboard_userId_user_id_fk'),
        ('project_v2_guided_session', 'projectV2GuidedSession_pkey', 'project_v2_guided_session_pkey'),
        ('project_v2_guided_session', 'projectV2GuidedSession_projectId_projectV2_id_fk', 'project_v2_guided_session_projectId_project_v2_id_fk'),
        ('project_v2_guided_session', 'projectV2GuidedSession_userId_user_id_fk', 'project_v2_guided_session_userId_user_id_fk'),
        ('project_v2_invitation', 'projectV2Invitation_inviteToken_unique', 'project_v2_invitation_inviteToken_unique'),
        ('project_v2_invitation', 'projectV2Invitation_invitedById_user_id_fk', 'project_v2_invitation_invitedById_user_id_fk'),
        ('project_v2_invitation', 'projectV2Invitation_invitedUserId_user_id_fk', 'project_v2_invitation_invitedUserId_user_id_fk'),
        ('project_v2_invitation', 'projectV2Invitation_pkey', 'project_v2_invitation_pkey'),
        ('project_v2_invitation', 'projectV2Invitation_projectId_projectV2_id_fk', 'project_v2_invitation_projectId_project_v2_id_fk'),
        ('project_v2_knowledge_base', 'projectV2KnowledgeBase_pkey', 'project_v2_knowledge_base_pkey'),
        ('project_v2_knowledge_base', 'projectV2KnowledgeBase_projectId_projectV2_id_fk', 'project_v2_knowledge_base_projectId_project_v2_id_fk'),
        ('project_v2_knowledge_base', 'projectV2KnowledgeBase_projectId_unique', 'project_v2_knowledge_base_projectId_unique'),
        ('project_v2_leaderboard', 'projectV2Leaderboard_pkey', 'project_v2_leaderboard_pkey'),
        ('project_v2_leaderboard', 'projectV2Leaderboard_projectId_projectV2_id_fk', 'project_v2_leaderboard_projectId_project_v2_id_fk'),
        ('project_v2_leaderboard', 'projectV2Leaderboard_userId_user_id_fk', 'project_v2_leaderboard_userId_user_id_fk'),
        ('project_v2_member', 'projectV2Member_pkey', 'project_v2_member_pkey'),
        ('project_v2_member', 'projectV2Member_projectId_projectV2_id_fk', 'project_v2_member_projectId_project_v2_id_fk'),
        ('project_v2_member', 'projectV2Member_userId_user_id_fk', 'project_v2_member_userId_user_id_fk'),
        ('project_v2_mock_session', 'projectV2MockSession_pkey', 'project_v2_mock_session_pkey'),
        ('project_v2_mock_session', 'projectV2MockSession_projectId_projectV2_id_fk', 'project_v2_mock_session_projectId_project_v2_id_fk'),
        ('project_v2_mock_session', 'projectV2MockSession_sprintId_projectV2Sprint_id_fk', 'project_v2_mock_session_sprintId_project_v2_sprint_id_fk'),
        ('project_v2_mock_session', 'projectV2MockSession_userId_user_id_fk', 'project_v2_mock_session_userId_user_id_fk'),
        ('project_v2_page', 'projectV2Page_pkey', 'project_v2_page_pkey'),
        ('project_v2_page', 'projectV2Page_projectId_projectV2_id_fk', 'project_v2_page_projectId_project_v2_id_fk'),
        ('project_v2_quiz', 'projectV2Quiz_pkey', 'project_v2_quiz_pkey'),
        ('project_v2_quiz', 'projectV2Quiz_projectId_projectV2_id_fk', 'project_v2_quiz_projectId_project_v2_id_fk'),
        ('project_v2_quiz', 'projectV2Quiz_projectId_unique', 'project_v2_quiz_projectId_unique'),
        ('project_v2_quiz_answer', 'projectV2QuizAnswer_attemptId_projectV2QuizAttempt_id_fk', 'project_v2_quiz_answer_attemptId_project_v2_quiz_attempt_id_fk'),
        ('project_v2_quiz_answer', 'projectV2QuizAnswer_pkey', 'project_v2_quiz_answer_pkey'),
        ('project_v2_quiz_answer', 'projectV2QuizAnswer_questionId_projectV2QuizQuestion_id_fk', 'project_v2_quiz_answer_questionId_project_v2_quiz_question_id_fk'),
        ('project_v2_quiz_attempt', 'projectV2QuizAttempt_pkey', 'project_v2_quiz_attempt_pkey'),
        ('project_v2_quiz_attempt', 'projectV2QuizAttempt_projectId_projectV2_id_fk', 'project_v2_quiz_attempt_projectId_project_v2_id_fk'),
        ('project_v2_quiz_attempt', 'projectV2QuizAttempt_quizId_projectV2Quiz_id_fk', 'project_v2_quiz_attempt_quizId_project_v2_quiz_id_fk'),
        ('project_v2_quiz_attempt', 'projectV2QuizAttempt_userId_user_id_fk', 'project_v2_quiz_attempt_userId_user_id_fk'),
        ('project_v2_quiz_question', 'projectV2QuizQuestion_pkey', 'project_v2_quiz_question_pkey'),
        ('project_v2_quiz_question', 'projectV2QuizQuestion_quizId_projectV2Quiz_id_fk', 'project_v2_quiz_question_quizId_project_v2_quiz_id_fk'),
        ('project_v2_resource', 'projectV2Resource_pkey', 'project_v2_resource_pkey'),
        ('project_v2_resource', 'projectV2Resource_projectId_projectV2_id_fk', 'project_v2_resource_projectId_project_v2_id_fk'),
        ('project_v2_resource', 'projectV2Resource_userId_user_id_fk', 'project_v2_resource_userId_user_id_fk'),
        ('project_v2_sprint', 'projectV2Sprint_createdBy_user_id_fk', 'project_v2_sprint_createdBy_user_id_fk'),
        ('project_v2_sprint', 'projectV2Sprint_pkey', 'project_v2_sprint_pkey'),
        ('project_v2_sprint', 'projectV2Sprint_projectId_projectV2_id_fk', 'project_v2_sprint_projectId_project_v2_id_fk'),
        ('project_v2_sprint_suggestion', 'projectV2SprintSuggestion_pkey', 'project_v2_sprint_suggestion_pkey'),
        ('project_v2_sprint_suggestion', 'projectV2SprintSuggestion_projectId_projectV2_id_fk', 'project_v2_sprint_suggestion_projectId_project_v2_id_fk'),
        ('project_v2_sprint_suggestion', 'projectV2SprintSuggestion_reviewedById_user_id_fk', 'project_v2_sprint_suggestion_reviewedById_user_id_fk'),
        ('project_v2_sprint_suggestion', 'projectV2SprintSuggestion_suggestedById_user_id_fk', 'project_v2_sprint_suggestion_suggestedById_user_id_fk'),
        ('project_v2_standup_config', 'projectV2StandupConfig_pkey', 'project_v2_standup_config_pkey'),
        ('project_v2_standup_config', 'projectV2StandupConfig_projectId_projectV2_id_fk', 'project_v2_standup_config_projectId_project_v2_id_fk'),
        ('project_v2_standup_entry', 'projectV2StandupEntry_configId_projectV2StandupConfig_id_fk', 'project_v2_standup_entry_configId_project_v2_standup_config_id_fk'),
        ('project_v2_standup_entry', 'projectV2StandupEntry_pkey', 'project_v2_standup_entry_pkey'),
        ('project_v2_submission', 'projectV2Submission_pkey', 'project_v2_submission_pkey'),
        ('project_v2_submission', 'projectV2Submission_projectId_projectV2_id_fk', 'project_v2_submission_projectId_project_v2_id_fk'),
        ('project_v2_submission', 'projectV2Submission_userId_user_id_fk', 'project_v2_submission_userId_user_id_fk'),
        ('project_v2_task', 'projectV2Task_pkey', 'project_v2_task_pkey'),
        ('project_v2_task', 'projectV2Task_projectV2Id_projectV2_id_fk', 'project_v2_task_projectV2Id_project_v2_id_fk'),
        ('project_v2_task', 'projectV2Task_sprintId_projectV2Sprint_id_fk', 'project_v2_task_sprintId_project_v2_sprint_id_fk'),
        ('project_v2_task_detail', 'projectV2TaskDetail_pkey', 'project_v2_task_detail_pkey'),
        ('project_v2_task_detail', 'projectV2TaskDetail_taskId_projectV2Task_id_fk', 'project_v2_task_detail_taskId_project_v2_task_id_fk'),
        ('project_v2_task_detail', 'projectV2TaskDetail_taskId_unique', 'project_v2_task_detail_taskId_unique'),
        ('question_answer', 'questionAnswer_interviewId_jobInterviewAssistant_id_fk', 'question_answer_interviewId_job_interview_assistant_id_fk'),
        ('question_answer', 'questionAnswer_pkey', 'question_answer_pkey'),
        ('random_practice_session', 'randomPracticeSession_pkey', 'random_practice_session_pkey'),
        ('random_practice_session', 'randomPracticeSession_userId_user_id_fk', 'random_practice_session_userId_user_id_fk'),
        ('recent_activity', 'recentActivity_pkey', 'recent_activity_pkey'),
        ('recent_activity', 'recentActivity_userId_user_id_fk', 'recent_activity_userId_user_id_fk'),
        ('resume_draft', 'resumeDraft_pkey', 'resume_draft_pkey'),
        ('resume_draft', 'resumeDraft_shareSlug_unique', 'resume_draft_shareSlug_unique'),
        ('resume_draft', 'resumeDraft_userId_user_id_fk', 'resume_draft_userId_user_id_fk'),
        ('resume_template', 'resumeTemplate_createdById_user_id_fk', 'resume_template_createdById_user_id_fk'),
        ('resume_template', 'resumeTemplate_pkey', 'resume_template_pkey'),
        ('resume_template', 'resumeTemplate_slug_unique', 'resume_template_slug_unique'),
        ('resume_template_generation', 'resumeTemplateGeneration_pkey', 'resume_template_generation_pkey'),
        ('resume_template_generation', 'resumeTemplateGeneration_templateId_resumeTemplate_id_fk', 'resume_template_generation_templateId_resume_template_id_fk'),
        ('resume_template_generation', 'resumeTemplateGeneration_userId_user_id_fk', 'resume_template_generation_userId_user_id_fk'),
        ('saved_job', 'savedJob_jobId_job_id_fk', 'saved_job_jobId_job_id_fk'),
        ('saved_job', 'savedJob_pkey', 'saved_job_pkey'),
        ('saved_job', 'savedJob_userId_user_id_fk', 'saved_job_userId_user_id_fk'),
        ('skill_endorsement', 'skillEndorsement_pkey', 'skill_endorsement_pkey'),
        ('skill_endorsement', 'skillEndorsement_skillId_skills_id_fk', 'skill_endorsement_skillId_skills_id_fk'),
        ('social_connection', 'socialConnection_pkey', 'social_connection_pkey'),
        ('social_connection', 'socialConnection_userId_user_id_fk', 'social_connection_userId_user_id_fk'),
        ('social_link', 'socialLink_pkey', 'social_link_pkey'),
        ('social_link', 'socialLink_userId_user_id_fk', 'social_link_userId_user_id_fk'),
        ('streak_reward', 'streakReward_pkey', 'streak_reward_pkey'),
        ('streak_reward', 'streakReward_userId_user_id_fk', 'streak_reward_userId_user_id_fk'),
        ('student_university_link', 'studentUniversityLink_departmentId_department_id_fk', 'student_university_link_departmentId_department_id_fk'),
        ('student_university_link', 'studentUniversityLink_pkey', 'student_university_link_pkey'),
        ('student_university_link', 'studentUniversityLink_universityId_university_id_fk', 'student_university_link_universityId_university_id_fk'),
        ('studio_chat_message', 'studioChatMessage_pkey', 'studio_chat_message_pkey'),
        ('studio_chat_message', 'studioChatMessage_studioId_studio_id_fk', 'studio_chat_message_studioId_studio_id_fk'),
        ('studio_code_block', 'studioCodeBlock_pkey', 'studio_code_block_pkey'),
        ('studio_code_block', 'studioCodeBlock_studioId_studio_id_fk', 'studio_code_block_studioId_studio_id_fk'),
        ('studio_flashcard_deck', 'studioFlashcardDeck_pkey', 'studio_flashcard_deck_pkey'),
        ('studio_flashcard_deck', 'studioFlashcardDeck_studioId_studio_id_fk', 'studio_flashcard_deck_studioId_studio_id_fk'),
        ('studio_flashcard_session', 'studioFlashcardSession_deckId_studioFlashcardDeck_id_fk', 'studio_flashcard_session_deckId_studio_flashcard_deck_id_fk'),
        ('studio_flashcard_session', 'studioFlashcardSession_pkey', 'studio_flashcard_session_pkey'),
        ('studio_flashcard_session', 'studioFlashcardSession_userId_user_id_fk', 'studio_flashcard_session_userId_user_id_fk'),
        ('studio_media_block', 'studioMediaBlock_pkey', 'studio_media_block_pkey'),
        ('studio_media_block', 'studioMediaBlock_studioId_studio_id_fk', 'studio_media_block_studioId_studio_id_fk'),
        ('studio_quiz', 'studioQuiz_pkey', 'studio_quiz_pkey'),
        ('studio_quiz', 'studioQuiz_studioId_studio_id_fk', 'studio_quiz_studioId_studio_id_fk'),
        ('studio_quiz_attempt', 'studioQuizAttempt_pkey', 'studio_quiz_attempt_pkey'),
        ('studio_quiz_attempt', 'studioQuizAttempt_quizId_studioQuiz_id_fk', 'studio_quiz_attempt_quizId_studio_quiz_id_fk'),
        ('studio_quiz_attempt', 'studioQuizAttempt_userId_user_id_fk', 'studio_quiz_attempt_userId_user_id_fk'),
        ('studio_step', 'studioStep_pkey', 'studio_step_pkey'),
        ('studio_step', 'studioStep_studioId_studio_id_fk', 'studio_step_studioId_studio_id_fk'),
        ('sub_transaction', 'subTransaction_creditTransactionId_creditTransaction_id_fk', 'sub_transaction_creditTransactionId_credit_transaction_id_fk'),
        ('sub_transaction', 'subTransaction_creditTransactionId_unique', 'sub_transaction_creditTransactionId_unique'),
        ('sub_transaction', 'subTransaction_pkey', 'sub_transaction_pkey'),
        ('template_purchase', 'templatePurchase_buyerId_user_id_fk', 'template_purchase_buyerId_user_id_fk'),
        ('template_purchase', 'templatePurchase_pkey', 'template_purchase_pkey'),
        ('template_purchase', 'templatePurchase_templateId_resumeTemplate_id_fk', 'template_purchase_templateId_resume_template_id_fk'),
        ('university_assignment', 'universityAssignment_classId_universityClass_id_fk', 'university_assignment_classId_university_class_id_fk'),
        ('university_assignment', 'universityAssignment_pkey', 'university_assignment_pkey'),
        ('university_class', 'universityClass_departmentId_department_id_fk', 'university_class_departmentId_department_id_fk'),
        ('university_class', 'universityClass_facultyId_universityMember_id_fk', 'university_class_facultyId_university_member_id_fk'),
        ('university_class', 'universityClass_pkey', 'university_class_pkey'),
        ('university_class', 'universityClass_universityId_university_id_fk', 'university_class_universityId_university_id_fk'),
        ('university_credit_transaction', 'universityCreditTransaction_pkey', 'university_credit_transaction_pkey'),
        ('university_credit_transaction', 'universityCreditTransaction_universityId_university_id_fk', 'university_credit_transaction_universityId_university_id_fk'),
        ('university_invitation', 'universityInvitation_inviteCode_unique', 'university_invitation_inviteCode_unique'),
        ('university_invitation', 'universityInvitation_pkey', 'university_invitation_pkey'),
        ('university_invitation', 'universityInvitation_universityId_university_id_fk', 'university_invitation_universityId_university_id_fk'),
        ('university_invoice', 'universityInvoice_invoiceNumber_unique', 'university_invoice_invoiceNumber_unique'),
        ('university_invoice', 'universityInvoice_pkey', 'university_invoice_pkey'),
        ('university_invoice', 'universityInvoice_universityId_university_id_fk', 'university_invoice_universityId_university_id_fk'),
        ('university_job', 'universityJob_pkey', 'university_job_pkey'),
        ('university_job', 'universityJob_universityId_university_id_fk', 'university_job_universityId_university_id_fk'),
        ('university_member', 'universityMember_departmentId_department_id_fk', 'university_member_departmentId_department_id_fk'),
        ('university_member', 'universityMember_pkey', 'university_member_pkey'),
        ('university_member', 'universityMember_universityId_university_id_fk', 'university_member_universityId_university_id_fk'),
        ('university_member_invitation', 'universityMemberInvitation_inviteCode_unique', 'university_member_invitation_inviteCode_unique'),
        ('university_member_invitation', 'universityMemberInvitation_invitedById_universityMember_id_fk', 'university_member_invitation_invitedById_university_member_id_fk'),
        ('university_member_invitation', 'universityMemberInvitation_pkey', 'university_member_invitation_pkey'),
        ('university_member_invitation', 'universityMemberInvitation_universityId_university_id_fk', 'university_member_invitation_universityId_university_id_fk'),
        ('university_payment', 'universityPayment_pkey', 'university_payment_pkey'),
        ('university_payment', 'universityPayment_universityId_university_id_fk', 'university_payment_universityId_university_id_fk'),
        ('university_submission', 'universitySubmission_assignmentId_universityAssignment_id_fk', 'university_submission_assignmentId_university_assignment_id_fk'),
        ('university_submission', 'universitySubmission_pkey', 'university_submission_pkey'),
        ('university_submission', 'universitySubmission_studentLinkId_studentUniversityLink_id_fk', 'university_submission_studentLinkId_student_university_link_id_fk'),
        ('university_subscription', 'universitySubscription_pkey', 'university_subscription_pkey'),
        ('university_subscription', 'universitySubscription_universityId_unique', 'university_subscription_universityId_unique'),
        ('university_subscription', 'universitySubscription_universityId_university_id_fk', 'university_subscription_universityId_university_id_fk'),
        ('user_achievement', 'userAchievement_pkey', 'user_achievement_pkey'),
        ('user_achievement', 'userAchievement_userId_user_id_fk', 'user_achievement_userId_user_id_fk'),
        ('user_assessment_stats', 'userAssessmentStats_pkey', 'user_assessment_stats_pkey'),
        ('user_assessment_stats', 'userAssessmentStats_userId_unique', 'user_assessment_stats_userId_unique'),
        ('user_assessment_stats', 'userAssessmentStats_userId_user_id_fk', 'user_assessment_stats_userId_user_id_fk'),
        ('user_dsa_tracking_entry', 'userDSATrackingEntry_pkey', 'user_dsa_tracking_entry_pkey'),
        ('user_dsa_tracking_entry', 'userDSATrackingEntry_userId_user_id_fk', 'user_dsa_tracking_entry_userId_user_id_fk'),
        ('user_education', 'userEducation_pkey', 'user_education_pkey'),
        ('user_education', 'userEducation_userId_user_id_fk', 'user_education_userId_user_id_fk'),
        ('user_exam_set', 'userExamSet_creatorId_user_id_fk', 'user_exam_set_creatorId_user_id_fk'),
        ('user_exam_set', 'userExamSet_pkey', 'user_exam_set_pkey'),
        ('user_exam_set', 'userExamSet_slug_unique', 'user_exam_set_slug_unique'),
        ('user_exam_set', 'userExamSet_topicId_assessmentTopic_id_fk', 'user_exam_set_topicId_assessment_topic_id_fk'),
        ('user_exam_set_answer', 'userExamSetAnswer_attemptId_userExamSetAttempt_id_fk', 'user_exam_set_answer_attemptId_user_exam_set_attempt_id_fk'),
        ('user_exam_set_answer', 'userExamSetAnswer_pkey', 'user_exam_set_answer_pkey'),
        ('user_exam_set_answer', 'userExamSetAnswer_questionId_userExamSetQuestion_id_fk', 'user_exam_set_answer_questionId_user_exam_set_question_id_fk'),
        ('user_exam_set_attempt', 'userExamSetAttempt_certificateId_unique', 'user_exam_set_attempt_certificateId_unique'),
        ('user_exam_set_attempt', 'userExamSetAttempt_examSetId_userExamSet_id_fk', 'user_exam_set_attempt_examSetId_user_exam_set_id_fk'),
        ('user_exam_set_attempt', 'userExamSetAttempt_pkey', 'user_exam_set_attempt_pkey'),
        ('user_exam_set_attempt', 'userExamSetAttempt_userId_user_id_fk', 'user_exam_set_attempt_userId_user_id_fk'),
        ('user_exam_set_like', 'userExamSetLike_examSetId_userExamSet_id_fk', 'user_exam_set_like_examSetId_user_exam_set_id_fk'),
        ('user_exam_set_like', 'userExamSetLike_pkey', 'user_exam_set_like_pkey'),
        ('user_exam_set_like', 'userExamSetLike_userId_user_id_fk', 'user_exam_set_like_userId_user_id_fk'),
        ('user_exam_set_purchase', 'userExamSetPurchase_examSetId_userExamSet_id_fk', 'user_exam_set_purchase_examSetId_user_exam_set_id_fk'),
        ('user_exam_set_purchase', 'userExamSetPurchase_pkey', 'user_exam_set_purchase_pkey'),
        ('user_exam_set_purchase', 'userExamSetPurchase_userId_user_id_fk', 'user_exam_set_purchase_userId_user_id_fk'),
        ('user_exam_set_question', 'userExamSetQuestion_examSetId_userExamSet_id_fk', 'user_exam_set_question_examSetId_user_exam_set_id_fk'),
        ('user_exam_set_question', 'userExamSetQuestion_pkey', 'user_exam_set_question_pkey'),
        ('user_level_progress', 'userLevelProgress_level_level_level_fk', 'user_level_progress_level_level_level_fk'),
        ('user_level_progress', 'userLevelProgress_pkey', 'user_level_progress_pkey'),
        ('user_level_progress', 'userLevelProgress_userId_user_id_fk', 'user_level_progress_userId_user_id_fk'),
        ('user_os_stats', 'userOSStats_pkey', 'user_os_stats_pkey'),
        ('user_os_stats', 'userOSStats_userId_unique', 'user_os_stats_userId_unique'),
        ('user_os_stats', 'userOSStats_userId_user_id_fk', 'user_os_stats_userId_user_id_fk'),
        ('user_practice_set', 'userPracticeSet_creatorId_user_id_fk', 'user_practice_set_creatorId_user_id_fk'),
        ('user_practice_set', 'userPracticeSet_pkey', 'user_practice_set_pkey'),
        ('user_practice_set', 'userPracticeSet_slug_unique', 'user_practice_set_slug_unique'),
        ('user_practice_set', 'userPracticeSet_subModuleId_assessmentSubModule_id_fk', 'user_practice_set_subModuleId_assessment_sub_module_id_fk'),
        ('user_practice_set', 'userPracticeSet_topicId_assessmentTopic_id_fk', 'user_practice_set_topicId_assessment_topic_id_fk'),
        ('user_practice_set_answer', 'userPracticeSetAnswer_attemptId_userPracticeSetAttempt_id_fk', 'user_practice_set_answer_attemptId_user_practice_set_attempt_id_fk'),
        ('user_practice_set_answer', 'userPracticeSetAnswer_pkey', 'user_practice_set_answer_pkey'),
        ('user_practice_set_answer', 'userPracticeSetAnswer_questionId_userPracticeSetQuestion_id_fk', 'user_practice_set_answer_questionId_user_practice_set_question_id_fk'),
        ('user_practice_set_attempt', 'userPracticeSetAttempt_pkey', 'user_practice_set_attempt_pkey'),
        ('user_practice_set_attempt', 'userPracticeSetAttempt_practiceSetId_userPracticeSet_id_fk', 'user_practice_set_attempt_practiceSetId_user_practice_set_id_fk'),
        ('user_practice_set_attempt', 'userPracticeSetAttempt_userId_user_id_fk', 'user_practice_set_attempt_userId_user_id_fk'),
        ('user_practice_set_like', 'userPracticeSetLike_pkey', 'user_practice_set_like_pkey'),
        ('user_practice_set_like', 'userPracticeSetLike_practiceSetId_userPracticeSet_id_fk', 'user_practice_set_like_practiceSetId_user_practice_set_id_fk'),
        ('user_practice_set_like', 'userPracticeSetLike_userId_user_id_fk', 'user_practice_set_like_userId_user_id_fk'),
        ('user_practice_set_purchase', 'userPracticeSetPurchase_pkey', 'user_practice_set_purchase_pkey'),
        ('user_practice_set_purchase', 'userPracticeSetPurchase_practiceSetId_userPracticeSet_id_fk', 'user_practice_set_purchase_practiceSetId_user_practice_set_id_fk'),
        ('user_practice_set_purchase', 'userPracticeSetPurchase_userId_user_id_fk', 'user_practice_set_purchase_userId_user_id_fk'),
        ('user_practice_set_question', 'userPracticeSetQuestion_pkey', 'user_practice_set_question_pkey'),
        ('user_practice_set_question', 'userPracticeSetQuestion_practiceSetId_userPracticeSet_id_fk', 'user_practice_set_question_practiceSetId_user_practice_set_id_fk'),
        ('user_profile', 'userProfile_pkey', 'user_profile_pkey'),
        ('user_profile', 'userProfile_userId_unique', 'user_profile_userId_unique'),
        ('user_profile', 'userProfile_userId_user_id_fk', 'user_profile_userId_user_id_fk'),
        ('user_project_v2_progress', 'userProjectV2Progress_pkey', 'user_project_v2_progress_pkey'),
        ('user_project_v2_progress', 'userProjectV2Progress_projectId_projectV2_id_fk', 'user_project_v2_progress_projectId_project_v2_id_fk'),
        ('user_project_v2_progress', 'userProjectV2Progress_userId_user_id_fk', 'user_project_v2_progress_userId_user_id_fk'),
        ('user_question_response', 'userQuestionResponse_interviewId_jobInterviewAssistant_id_fk', 'user_question_response_interviewId_job_interview_assistant_id_fk'),
        ('user_question_response', 'userQuestionResponse_pkey', 'user_question_response_pkey'),
        ('user_skill', 'userSkill_pkey', 'user_skill_pkey'),
        ('user_skill', 'userSkill_userId_user_id_fk', 'user_skill_userId_user_id_fk'),
        ('user_stats', 'userStats_pkey', 'user_stats_pkey'),
        ('user_stats', 'userStats_userId_unique', 'user_stats_userId_unique'),
        ('user_stats', 'userStats_userId_user_id_fk', 'user_stats_userId_user_id_fk'),
        ('user_task_v2_assessment', 'userTaskV2Assessment_pkey', 'user_task_v2_assessment_pkey'),
        ('user_task_v2_assessment', 'userTaskV2Assessment_taskId_projectV2Task_id_fk', 'user_task_v2_assessment_taskId_project_v2_task_id_fk'),
        ('user_task_v2_assessment', 'userTaskV2Assessment_userId_user_id_fk', 'user_task_v2_assessment_userId_user_id_fk'),
        ('user_task_v2_detail_access', 'userTaskV2DetailAccess_pkey', 'user_task_v2_detail_access_pkey'),
        ('user_task_v2_detail_access', 'userTaskV2DetailAccess_taskDetailId_projectV2TaskDetail_id_fk', 'user_task_v2_detail_access_taskDetailId_project_v2_task_detail_id_fk'),
        ('user_task_v2_detail_access', 'userTaskV2DetailAccess_userId_user_id_fk', 'user_task_v2_detail_access_userId_user_id_fk'),
        ('user_task_v2_status', 'userTaskV2Status_pkey', 'user_task_v2_status_pkey'),
        ('user_task_v2_status', 'userTaskV2Status_progressId_userProjectV2Progress_id_fk', 'user_task_v2_status_progressId_user_project_v2_progress_id_fk'),
        ('user_task_v2_status', 'userTaskV2Status_projectId_projectV2_id_fk', 'user_task_v2_status_projectId_project_v2_id_fk'),
        ('user_task_v2_status', 'userTaskV2Status_taskId_projectV2Task_id_fk', 'user_task_v2_status_taskId_project_v2_task_id_fk'),
        ('user_task_v2_status', 'userTaskV2Status_userId_user_id_fk', 'user_task_v2_status_userId_user_id_fk'),
        ('work_experience', 'workExperience_pkey', 'work_experience_pkey'),
        ('work_experience', 'workExperience_userId_user_id_fk', 'work_experience_userId_user_id_fk'),
        ('xp_transaction', 'xpTransaction_pkey', 'xp_transaction_pkey'),
        ('xp_transaction', 'xpTransaction_userId_user_id_fk', 'xp_transaction_userId_user_id_fk');

    INSERT INTO _e (old_name, new_name) VALUES
        ('ActivityType', 'activity_type'),
        ('AdminInviteStatus', 'admin_invite_status'),
        ('AdminRole', 'admin_role'),
        ('AdminStatus', 'admin_status'),
        ('ApplicationActivityType', 'application_activity_type'),
        ('ApplicationStatus', 'application_status'),
        ('AssessmentLanguage', 'assessment_language'),
        ('AssessmentMode', 'assessment_mode'),
        ('AssessmentQuestionType', 'assessment_question_type'),
        ('AssessmentType', 'assessment_type'),
        ('CommentEntityType', 'comment_entity_type'),
        ('CompanyInvitationStatus', 'company_invitation_status'),
        ('CompanyMemberJobTitle', 'company_member_job_title'),
        ('CompanyMemberRole', 'company_member_role'),
        ('CompanyVerificationStatus', 'company_verification_status'),
        ('ContentSource', 'content_source'),
        ('ContributionStatus', 'contribution_status'),
        ('ContributionType', 'contribution_type'),
        ('CreditRequestStatus', 'credit_request_status'),
        ('CreditType', 'credit_type'),
        ('Currency', 'currency'),
        ('EmploymentType', 'employment_type'),
        ('FeatureSuggestionStatus', 'feature_suggestion_status'),
        ('FeatureSuggestionType', 'feature_suggestion_type'),
        ('FeedbackCategory', 'feedback_category'),
        ('FeedbackStatus', 'feedback_status'),
        ('FollowRequestStatus', 'follow_request_status'),
        ('HiringInvoiceStatus', 'hiring_invoice_status'),
        ('HiringPaymentStatus', 'hiring_payment_status'),
        ('HiringSubscriptionPlan', 'hiring_subscription_plan'),
        ('HiringSubscriptionStatus', 'hiring_subscription_status'),
        ('IdeaType', 'idea_type'),
        ('InterviewCardDifficulty', 'interview_card_difficulty'),
        ('InterviewFormat', 'interview_format'),
        ('InterviewRoundType', 'interview_round_type'),
        ('IssueDifficulty', 'issue_difficulty'),
        ('JobLocationType', 'job_location_type'),
        ('JobMockSessionType', 'job_mock_session_type'),
        ('JobMockStatus', 'job_mock_status'),
        ('JobStatus', 'job_status'),
        ('JobVisibility', 'job_visibility'),
        ('KnowMeDataType', 'know_me_data_type'),
        ('KnowMeJobStatus', 'know_me_job_status'),
        ('KnowMeJobType', 'know_me_job_type'),
        ('KnowMePlatform', 'know_me_platform'),
        ('KnowMePrivacy', 'know_me_privacy'),
        ('KnowMeQuestionCategory', 'know_me_question_category'),
        ('KnowMeStatus', 'know_me_status'),
        ('KnowMeSyncStatus', 'know_me_sync_status'),
        ('KnowMeViewerType', 'know_me_viewer_type'),
        ('LearnDifficulty', 'learn_difficulty'),
        ('LearnRequestStatus', 'learn_request_status'),
        ('LearnStatus', 'learn_status'),
        ('LearnStepType', 'learn_step_type'),
        ('MemberInviteStatus', 'member_invite_status'),
        ('MockCategory', 'mock_category'),
        ('MockLevel', 'mock_level'),
        ('MockSessionType', 'mock_session_type'),
        ('Module', 'module'),
        ('NotificationType', 'notification_type'),
        ('OSCertificationStatus', 'os_certification_status'),
        ('OSContributionStatus', 'os_contribution_status'),
        ('OSContributionType', 'os_contribution_type'),
        ('OSIssueDifficulty', 'os_issue_difficulty'),
        ('OSIssueStatus', 'os_issue_status'),
        ('OSLearnLabType', 'os_learn_lab_type'),
        ('OSLearnModuleType', 'os_learn_module_type'),
        ('OSProjectCategory', 'os_project_category'),
        ('OSProjectStatus', 'os_project_status'),
        ('OSProjectType', 'os_project_type'),
        ('OpenSourceDifficulty', 'open_source_difficulty'),
        ('PathfinderCategory', 'pathfinder_category'),
        ('PathfinderGoalDuration', 'pathfinder_goal_duration'),
        ('PathfinderLevel', 'pathfinder_level'),
        ('PathfinderStatus', 'pathfinder_status'),
        ('PaymentStatus', 'payment_status'),
        ('Platform', 'platform'),
        ('PortfolioProjectSource', 'portfolio_project_source'),
        ('PracticeDifficulty', 'practice_difficulty'),
        ('PracticeMode', 'practice_mode'),
        ('PracticeModule', 'practice_module'),
        ('PracticeSessionStatus', 'practice_session_status'),
        ('ProfileLayout', 'profile_layout'),
        ('ProfileTheme', 'profile_theme'),
        ('ProfileVisibility', 'profile_visibility'),
        ('ProjectErrorCategory', 'project_error_category'),
        ('ProjectErrorSeverity', 'project_error_severity'),
        ('ProjectErrorStatus', 'project_error_status'),
        ('ProjectIdeaStatus', 'project_idea_status'),
        ('ProjectStatus', 'project_status'),
        ('ProjectTier', 'project_tier'),
        ('ProjectV2Difficulty', 'project_v2_difficulty'),
        ('ProjectV2InvitationStatus', 'project_v2_invitation_status'),
        ('ProjectV2MemberRole', 'project_v2_member_role'),
        ('ProjectV2Visibility', 'project_v2_visibility'),
        ('QuestionDifficulty', 'question_difficulty'),
        ('QuizDifficulty', 'quiz_difficulty'),
        ('QuizQuestionType', 'quiz_question_type'),
        ('QuizV2Difficulty', 'quiz_v2_difficulty'),
        ('ResourceType', 'resource_type'),
        ('Role', 'role'),
        ('SemesterType', 'semester_type'),
        ('SkillCategory', 'skill_category'),
        ('SocialProvider', 'social_provider'),
        ('SprintSuggestionStatus', 'sprint_suggestion_status'),
        ('StudentVerificationStatus', 'student_verification_status'),
        ('StudioBlockType', 'studio_block_type'),
        ('StudioCategory', 'studio_category'),
        ('StudioMediaType', 'studio_media_type'),
        ('StudioSource', 'studio_source'),
        ('StudioStepStatus', 'studio_step_status'),
        ('StudioStepType', 'studio_step_type'),
        ('StudioVisibility', 'studio_visibility'),
        ('SubGoalStatus', 'sub_goal_status'),
        ('SubmissionGradingStatus', 'submission_grading_status'),
        ('SuggestionSource', 'suggestion_source'),
        ('SyncStatus', 'sync_status'),
        ('TaskAssessmentType', 'task_assessment_type'),
        ('TaskKanbanStatus', 'task_kanban_status'),
        ('TemplateCategory', 'template_category'),
        ('TemplateStyle', 'template_style'),
        ('UniversityAssignmentStatus', 'university_assignment_status'),
        ('UniversityAssignmentType', 'university_assignment_type'),
        ('UniversityJobVisibility', 'university_job_visibility'),
        ('UniversityMemberInviteStatus', 'university_member_invite_status'),
        ('UniversityMemberJobTitle', 'university_member_job_title'),
        ('UniversityMemberRole', 'university_member_role'),
        ('UniversitySubscriptionPlan', 'university_subscription_plan'),
        ('UniversitySubscriptionStatus', 'university_subscription_status'),
        ('UniversityType', 'university_type'),
        ('UniversityVerificationStatus', 'university_verification_status'),
        ('UserContentStatus', 'user_content_status'),
        ('UserProjectV2Status', 'user_project_v2_status'),
        ('VerificationSectionStatus', 'verification_section_status'),
        ('XpTransactionProps', 'xp_transaction_props');

    ---------------------------------------------------------------------------
    -- 1. Tables
    ---------------------------------------------------------------------------
    FOR r IN
        SELECT m.old_name, m.new_name FROM _t m
        JOIN pg_class c     ON c.relname = m.old_name AND c.relkind = 'r'
        JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
        WHERE NOT EXISTS (
            SELECT 1 FROM pg_class c2
            JOIN pg_namespace n2 ON n2.oid = c2.relnamespace
            WHERE n2.nspname = 'public' AND c2.relname = m.new_name)
    LOOP
        EXECUTE format('ALTER TABLE public.%I RENAME TO %I', r.old_name, r.new_name);
    END LOOP;

    ---------------------------------------------------------------------------
    -- 2. Constraints -- keyed on the NEW table name, since step 1 already ran.
    ---------------------------------------------------------------------------
    FOR r IN
        SELECT m.tbl, m.old_name, m.new_name FROM _c m
        JOIN pg_class t      ON t.relname = m.tbl AND t.relkind = 'r'
        JOIN pg_namespace n  ON n.oid = t.relnamespace AND n.nspname = 'public'
        JOIN pg_constraint c ON c.conrelid = t.oid AND c.conname = m.old_name
        WHERE NOT EXISTS (
            SELECT 1 FROM pg_constraint c2
            WHERE c2.conrelid = t.oid AND c2.conname = m.new_name)
    LOOP
        EXECUTE format('ALTER TABLE public.%I RENAME CONSTRAINT %I TO %I',
                       r.tbl, r.old_name, r.new_name);
    END LOOP;

    ---------------------------------------------------------------------------
    -- 3. Enum types
    ---------------------------------------------------------------------------
    FOR r IN
        SELECT m.old_name, m.new_name FROM _e m
        JOIN pg_type t      ON t.typname = m.old_name AND t.typtype = 'e'
        JOIN pg_namespace n ON n.oid = t.typnamespace AND n.nspname = 'public'
        WHERE NOT EXISTS (
            SELECT 1 FROM pg_type t2
            JOIN pg_namespace n2 ON n2.oid = t2.typnamespace
            WHERE n2.nspname = 'public' AND t2.typname = m.new_name)
    LOOP
        EXECUTE format('ALTER TYPE public.%I RENAME TO %I', r.old_name, r.new_name);
    END LOOP;

    DROP TABLE IF EXISTS pg_temp._t;
    DROP TABLE IF EXISTS pg_temp._c;
    DROP TABLE IF EXISTS pg_temp._e;
END $$;
